include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  language:
    strict-casts: true

linter:
  rules:
    always_declare_return_types: true
    annotate_overrides: true
    cancel_subscriptions: true
    close_sinks: true
    collection_methods_unrelated_type: true
    no_self_assignments: true
    throw_in_finally: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    use_super_parameters: true
    no_leading_underscores_for_local_identifiers: false
    avoid_renaming_method_parameters: false
    constant_identifier_names: false
    library_private_types_in_public_api: false
