name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  charts_common:
    name: charts_common_maintained tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: ['3.0.0', 'stable']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
        working-directory: charts_common_maintained
      - name: Analyze
        run: dart analyze --fatal-infos
        working-directory: charts_common_maintained
      - name: Run tests
        run: dart test
        working-directory: charts_common_maintained

  charts_flutter:
    name: charts_flutter_maintained tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [stable]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
      - name: Install dependencies
        run: flutter pub get
        working-directory: charts_flutter_maintained
      - name: Analyze
        run: flutter analyze
        working-directory: charts_flutter_maintained
      - name: Run tests
        run: flutter test
        working-directory: charts_flutter_maintained
